version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    restart: unless-stopped
    networks:
      - marslog-net

  php-ui:
  image: php:8.1-apache
  volumes:
    - ./frontend:/var/www/html
    - ./data:/var/www/html/data        # ✅ สำคัญ! ให้ container เห็น users.json
  ports:
    - "8885:80"
  restart: unless-stopped
  networks:
    - marslog-net


  flask-api:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["python3", "app.py"]
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - marslog-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - marslog-net

  agent-server:
    image: alpine
    command: sh -c 'while true; do sleep 5; done'
    restart: unless-stopped
    networks:
      - marslog-net

  alert-service:
    image: alpine
    command: sh -c 'while true; do sleep 5; done'
    restart: unless-stopped
    networks:
      - marslog-net

networks:
  marslog-net:
